### ISSUE TITLE
Create release GH action

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/autowrap#114]
Best with a GH Actions job that checks agreement of all occurrences of the version, tags/branches and uploads to pip.

**Comment by timosachsenberg** [comment]
ok this would be the publishing part I guess?
```
  # Upload the wheels (the action only runs on ubuntu slaves)
  publish:
    needs: [test] # doesn't really NEED it but we want the tests to pass first
    runs-on: ubuntu-latest
    steps:
    # haha github is just ridiculous.. not getting their actions to do basic stuff for years
    - name: Download artifacts
      uses: actions/download-artifact@v1.0.0
      with:
          name: Linux-wheels
    - name: Download artifacts
      uses: actions/download-artifact@v1.0.0
      with:
          name: Windows-wheels
    - name: Download artifacts
      uses: actions/download-artifact@v1.0.0
      with:
          name: macOS-wheels

    - name: Merge all artifacts
      run: |
            mkdir wheels
            cp -lr *-wheels/* wheels/
            pwd
            ls -la wheels/

    - name: Publish package to PyPI
      if: "contains(github.ref, 'Release')"
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_api_token_release }}
        packages_dir: ${{ github.workspace }}/wheels
```
